# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Q0YjQHGIraDX2AFaL58JCpLCa58zrgk
"""

import streamlit as st

# Set up the title
st.title("Find the Largest Among Three Numbers")

# Input fields for three numbers
num1 = st.number_input("Enter the first number:")
num2 = st.number_input("Enter the second number:")
num3 = st.number_input("Enter the third number:")

# Button to find the largest number
if st.button("Find the Largest"):
    if num1 > num2 and num1 > num3:
        largest = num1
    elif num2 > num1 and num2 > num3:
        largest = num2
    else:
        largest = num3

    st.success(f"The largest number among the three is: {largest}")

